### ISSUE TITLE
IntersectionObserver: now in Edge (15), Firefox (55, Nightly)

### ISSUE THREAD

**Issue by fvsch** [notwaldorf/lazy-image#1]
Hi,

I chanced upon the https://meowni.ca/lazy-image/ demo it saw the IntersectionObserver demo working well, then the text said “Only works in Chrome” and I was confused because I’m using Firefox. :P

So, it turns out that:
- IntersectionObserver landed in Edge 15 (stable).
- And it seems to be enabled by default in Firefox Nightly (55), which I was using. That’s a fairly recent change, so caniuse hasn’t picked it up yet.
- [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=159475) shows no sign of being near completion, but who knows.

IMO there’s no rush to update this information, but once the Fx implementation is in or near a stable release it’ll be worth updating it.

**Comment by notwaldorf** [comment]
I'll update the copy, thanks!
