### ISSUE TITLE
No srcset?

### ISSUE THREAD

**Issue by dgrammatiko** [notwaldorf/lazy-image#2]
@notwaldorf by adding few more lines, this custom element could support image srcset, which by the way is kinda standard these days.
So https://github.com/notwaldorf/lazy-image/blob/master/lazy-image.js#L17 one more line here `this._srcset = null;`
then
```js
  get srcset() { return this._srcset; }
  set srcset(value) {
    this._srcset = value;
    if (this._srcset)
      this._maybeLoadImage();
  }
```
and
```js
  _maybeLoadImage() {
    if (this._active) {
      this._img.src = this._src;
      this._img.srcset = this._srcset;
      //this._img.style.display = 'block';
    } else {
      this._img.src = '';
      this._img.srcaet = '';
      //this._img.style.display = 'none';
    }
  }
```

Also the tricky part: some code to get the window width and assign the right path from the srcset to the src

**Comment by cedeber** [comment]
Based on this component idea, I wrote a similar component that supports `<source>` and so `srcset`. [Here the code to get the correct srcset path from multiple source](https://github.com/frontools/frontools/blob/master/src/lazy-picture.ts#L109) (typescript)

[Demo](https://frontools.rocks/frontools/demos/lazy-picture.html) ([html source](https://github.com/frontools/frontools/blob/master/demos/lazy-picture.html) and [js source](https://github.com/frontools/frontools/blob/master/demos/js/lazy-picture.js))

**Comment by dgrammatiko** [comment]
@cedeber nice one!

**Comment by notwaldorf** [comment]
Ive added srcset support a while back, ps.
